name: ci apps/ui

on:
  pull_request:
    branches: [main]
    paths:
      - "apps/ui/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./apps/ui
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
        with:
          cache: "yarn"

      - name: Build application
        working-directory: ./apps/ui
        run: yarn build

      - name: Run static chacking
        working-directory: ./apps/ui
        run: yarn lint --quiet

      - name: Run tests
        working-directory: ./apps/ui
        run: yarn test
